ministryofjustice/hmpps-education-employment-ui

integration_tests/e2e/workExperience.cy.ts
integration_tests/pages/workExperience.ts
server/routes/addressLookup.ts
server/routes/createProfile/index.ts
server/routes/createProfile/jobOfParticularInterest/validationSchema.test.ts
server/routes/createProfile/jobOfParticularInterest/validationSchema.ts
server/routes/createProfile/workExperience/index.ts
server/routes/createProfile/workExperience/validationSchema.test.ts
server/routes/createProfile/workExperience/validationSchema.ts
server/routes/createProfile/workExperience/workExperienceController.test.ts
server/routes/createProfile/workExperience/workExperienceController.ts
server/views/pages/createProfile/workExperience/index.njk

ESWE-382_work_experience_screen

---

package-lock.json
package.json

Update Typescript & govuk frontend versions to solve: https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-employment-ui/277/workflows/8c0b46a4-f8a8-4947-bc20-496caa03fc89/jobs/980

ESWE-460_trivy_scan_error

---

package-lock.json

**What does this pull request do?**
This fixes vulnerability issue caused by old version of formidable and its transitive dependency
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-employment-ui/303/workflows/94d7f4d8-f56f-41ec-a768-0c3a87396c05/jobs/1085
**Reviewers**

ESWE-464_trivy_scan_error

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
package-lock.json
package.json

**What does this pull request do?**
This corrects the service host name as created through the helm chart so that traffic is enabled between DPS home page and the ESWE cohort list page, and bump up Typescript version. 
**Reviewers**

ESWE-347_entering_the_service_card

---

.circleci/config.yml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

👷 Enable PreProd and Prod deployments

ESWE-466 Enable PreProd and Prod Deployments

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

ESWE-473 - CircleCI security changes

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

🔧 Change ingress URL for dev
🔧 Change ingress URL for preprod
🔧 Change ingress URL for prod

ESWE-474 - Domain Change

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Missed these in the previous PR 🤦‍♂️
🔧 Update INGRESS_URL

ESWE-474 - Ingress URL change

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

ESWE-474 Test ingress 

---

integration_tests/e2e/changeStatus.cy.ts
server/routes/changeStatus/newStatusPause/newStatusPauseController.test.ts
server/routes/changeStatus/newStatusPause/newStatusPauseController.ts

🐛 Add id to template data
✅ Updated tests

ESWE-493 - Change Status, Return to profile link returns 404

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Add_missing_env_variables Updated deployment variables

---

server/constants/contentLookup/trainingAndQualifications.ts
server/views/pages/createProfile/trainingAndQualifications/index.njk

- Corrected Driving license words and position

ESWE-506_training_page_driving_license

---

helm_deploy/hmpps-education-employment-ui/values.yaml

Update IP allowed list in DEV ONLY to give the accessibility audit team, UserVision, access to our service.
More info about the IP, including procy IP range if needed - https://www.whatismyip.com/212.38.92.42/
**Reviewers**

ESWE-516_add_uservision_to_allowed_list_in_dev

---

server/routes/accessibilityStatement/accessibilityStatementController.ts
server/routes/accessibilityStatement/index.ts
server/routes/index.ts
server/views/pages/accessibilityStatement/index.njk
server/views/partials/footer.njk
server/views/partials/layout.njk

- Added new page
- Added link in footer

Eswe 457 accessibility statement

---

helm_deploy/values-dev.yaml
server/data/prisonerSearch/prisonerSearchClient.ts

- Updated env for more data in dev
- Updated search logic

missing_search_option updated search options and weeks for dev

---

helm_deploy/hmpps-education-employment-ui/values.yaml
server/config.ts
server/utils/nunjucksSetup.ts
server/views/partials/layout.njk

Setup Google Analytics to track basic actions.
**Reviewers**

ESWE-488_setup_google_analytics_ga4

---

integration_tests/e2e/cohortList.cy.ts
package-lock.json
server/data/prisonerSearch/prisonerSearchClient.ts
server/middleware/resolvers/getCohortListResolver.test.ts
server/middleware/resolvers/getCohortListResolver.ts
server/middleware/resolvers/getCurrentOffenderActivitiesResolver.ts
server/middleware/resolvers/getEmployabilitySkillsResolver.test.ts
server/middleware/resolvers/getEmployabilitySkillsResolver.ts
server/middleware/resolvers/getKeyworkerByIdResolver.ts
server/middleware/resolvers/getLatestAssessmentResolver.test.ts
server/middleware/resolvers/getLatestAssessmentResolver.ts
server/middleware/resolvers/getLearnerEducationResolver.test.ts
server/middleware/resolvers/getLearnerEducationResolver.ts
server/middleware/resolvers/getNeurodivergenceResolver.test.ts
server/middleware/resolvers/getNeurodivergenceResolver.ts
server/middleware/resolvers/getNotesResolver.ts
server/middleware/resolvers/getPomByIdResolver.test.ts
server/middleware/resolvers/getPomByIdResolver.ts
server/middleware/resolvers/getPrisonerByIdResolver.ts
server/middleware/resolvers/getProfileByIdResolver.ts
server/middleware/resolvers/getUnacceptableAbsencesCountResolver.ts
server/middleware/resolvers/utils.ts
server/services/allocationManagerService.ts
server/services/curiousEsweService.ts
server/services/keyworkerService.ts
server/services/prisonSearchService.ts
server/services/prisonService.ts
server/services/userService.ts
server/services/whereaboutsService.ts

DO NOT MERGE JUST APPROVE PLEASE. NOT FOR THIS RELEASE
Move all but our own API calls to use the service account.

Eswe 504 service account implementation

---

assets/sass/application.sass
server/routes/actions/editAction/editActionController.test.ts
server/routes/actions/editAction/editActionController.ts
server/routes/actions/editAction/index.ts
server/routes/workProfile/workProfileController.ts
server/views/pages/actions/editAction/index.njk
server/views/pages/actions/editAction/partials/_notes.njk

- Multiple accessibility issues

Eswe 545 accessibility issue

---

server/views/macros/pagination/macro.njk
server/views/pages/cohortList/partials/_cohortTable.njk

Ensure that link text makes sense in isolation, without the visual context.
https://uv2880-work-readiness-service.uservisionaccessibility.co.uk/pagination-links-unclear-medium.html
**Reviewers**

ESWE-553_pagination_link_unclear_accessibility

---

README.md

Define app + steps required to run locally.
**Reviewers**
@gary-dutton-moj 
@Paul Massey

ESWE-568_readme_text

---

server/config.ts
server/middleware/setUpStaticResources.ts

Cache static resources for 1 hour
@see: https://github.com/ministryofjustice/hmpps-template-typescript/pull/178/files

Template changes

---

server/routes/changeStatus/newStatus/newStatusController.test.ts
server/routes/changeStatus/newStatus/newStatusController.ts
server/routes/changeStatus/newStatusPause/newStatusPauseController.test.ts
server/routes/changeStatus/newStatusPause/newStatusPauseController.ts
server/routes/createProfile/abilityToWork/abilityToWorkController.test.ts
server/routes/createProfile/abilityToWork/abilityToWorkController.ts
server/views/pages/workProfile/partials/_abilityToWorkSection.njk
server/views/pages/workProfile/partials/_supportDeclinedSection.njk
server/views/pages/workProfile/partials/_toDoListSection.njk
server/views/pages/workProfile/partials/_workExperienceSection.njk
server/views/pages/workProfile/partials/_workInterestsSection.njk

- Accessibility fixes
- From fixes

Eswe 593 accessibility fixes

---

server/views/pages/accessibilityStatement/index.njk

ESWE-522_update_accessibility_statement Updated statement

---

package-lock.json
server/data/models/createProfileRequest.ts
server/data/models/editProfileRequest.ts
server/data/prisonerProfile/interfaces/createProfileRequestArgs.ts
server/data/prisonerProfile/interfaces/prisonerProfile.ts
server/data/prisonerProfile/interfaces/profileDataSection.ts
server/data/prisonerProfile/interfaces/updatePrisonerProfile.ts
server/routes/createProfile/checkYourAnswers/checkYourAnswersController.ts

Allow prisoner location (prison name) to be stored when:
-  profile is created 
- status is changed from 'does not need support' to 'needs support'
This will allow prisoners to be grouped by location when creating/running reports.
**Reviewers**

ESWE-645_store_prisoner_location

---

helm_deploy/hmpps-education-employment-ui/values.yaml
server/config.ts
server/utils/urlParameterEncryption.ts

Include passphrase in config
Passphrase added to secret in dev, preprod and prod

ESWE-739 - Passphrase

---

assets/sass/components/_external-header-bar.scss
assets/sass/components/_footer.scss
assets/sass/components/_header-bar.scss
server/views/partials/layout.njk

Fix dps header implementation after component changes

ESWE-748-implement-dps-header-fix fix dps header issue

---

helm_deploy/hmpps-education-employment-ui/Chart.yaml

Upgrade generic-service to latest

ESWE-752 - Upgrade Helm Charts 

---

assets/js/card.js
assets/sass/application.sass
assets/sass/components/_card.scss
helm_deploy/values-dev.yaml
package-lock.json
server/config.ts
server/data/nomisUserRolesApi/nomisUserRolesApiClient.ts
server/middleware/resolvers/getCandidateMatchingResolver.ts
server/routes/candidateMatching/candidateMatchingController.test.ts
server/routes/candidateMatching/candidateMatchingController.ts
server/routes/candidateMatching/index.test.ts
server/routes/candidateMatching/index.ts
server/routes/index.ts
server/services/candidateMatchingService.test.ts
server/services/candidateMatchingService.ts
server/services/index.ts
server/utils/utils.ts
server/views/pages/candidateMatching/index.njk
server/views/pages/candidateMatching/partials/card.njk

ESWE-799: new subpage for WRS (styling to be revised as discussed!)
**Reviewers**

ESWE-799_home_page

---

assets/sass/application.sass

Fix status filter box which has been impacted by a recent dps css change.
**Reviewers**

ESWE-812_fix_status_filter_layout

---

helm_deploy/values-dev.yaml

Fix deployment error (https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-employment-ui/1194/workflows/e6136d6b-adc0-437e-8538-a345e1fda464/jobs/4867)
**Reviewers**

ESWE-829_add_missing_job_api

---

integration_tests/e2e/workProfile.cy.ts
integration_tests/mockApis/deliusIntegrationApi.ts
integration_tests/pages/workProfile.ts
server/data/deliusIntegrationApi/deliusIntegrationApiClient.ts
server/data/deliusIntegrationApi/getPrisonerAddressResult.ts
server/data/jobApi/jobApiClient.ts
server/middleware/resolvers/getAllProfileDataResolver.test.ts
server/middleware/resolvers/getAllProfileDataResolver.ts
server/middleware/resolvers/getJobDetailsResolver.ts
server/middleware/resolvers/getMatchedJobsResolver.ts
server/middleware/resolvers/getPrisonerAddressByIdResolver.test.ts
server/middleware/resolvers/getPrisonerAddressByIdResolver.ts
server/middleware/resolvers/utils/getJobDetails.ts
server/middleware/resolvers/utils/getPrisonerAddressById.test.ts
server/middleware/resolvers/utils/getPrisonerAddressById.ts
server/routes/candidateMatching/jobDetails/index.test.ts
server/routes/candidateMatching/jobDetails/index.ts
server/routes/candidateMatching/jobDetails/jobDetailsController.test.ts
server/routes/candidateMatching/jobDetails/jobDetailsController.ts
server/routes/candidateMatching/matchedJobs/index.test.ts
server/routes/candidateMatching/matchedJobs/index.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.test.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.ts
server/routes/workProfile/workProfileController.ts
server/services/deliusIntegrationService.test.ts
server/services/deliusIntegrationService.ts
server/services/jobService.test.ts
server/services/jobService.ts
server/views/pages/candidateMatching/jobDetails/index.njk
server/views/pages/workProfile/partials/_profileHeader.njk

A3427EA is a record in dev with an address

Eswe 863 prisoner release area

---

assets/sass/application.sass

css_fix_radios Fixed label width

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

update prison api endpoint in preprod
**Reviewers**

Apply patches

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
package-lock.json
package.json

This PR will:
- fix outdated govuk-frontend
- add missing env variables
**Reviewers**

Preprod deployment error

---

integration_tests/e2e/candidateMatching/viewJobDetails.cy.ts
integration_tests/mockApis/jobApi.ts
integration_tests/pages/candidateMatching/jobDetails.ts
server/data/jobApi/getJobDetailsResponse.ts
server/data/jobApi/jobApiClient.ts
server/middleware/resolvers/getJobDetailsResolver.ts
server/middleware/resolvers/utils/getJobDetails.test.ts
server/middleware/resolvers/utils/getJobDetails.ts
server/services/jobService.test.ts
server/services/jobService.ts
server/viewModels/jobDetailsViewModel.test.ts
server/viewModels/jobDetailsViewModel.ts
server/views/pages/candidateMatching/jobDetails/index.njk

- Implemented new job details endpoint

ESWE-1000_implement_job_details_endpoint

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.ts
server/routes/homePage/homePageController.test.ts
server/routes/homePage/homePageController.ts

- Added feature flag for reporting home page tile
- Added config for tile and link
- Fixed unit tests to correctly test homepage controller

ESWE-1094_add_reporting_feature_flag

---

helm_deploy/hmpps-education-employment-ui/values.yaml
package-lock.json
package.json
server/config.ts
server/utils/nunjucksSetup.ts
server/views/partials/layout.njk
tsconfig.json

Set up Google Tag Manager so tracking can start from the Job upload tile.

ESWE-1103: setup and configure google tag manager

---

server/views/pages/candidateMatching/archivedJobs/partials/_archivedJobsTable.njk
server/views/pages/candidateMatching/jobDetails/index.njk
server/views/pages/candidateMatching/jobsOfInterest/partials/_jobsOfInterestTable.njk

Removed legacy city and town fields

Fix_remove_city_from_distance_blocks 

---

server/data/jobApi/getMatchedJobsClosingSoonResponse.ts
server/data/jobApi/jobApiClient.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.test.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.ts
server/routes/candidateMatching/matchedJobs/validationSchema.test.ts
server/routes/candidateMatching/matchedJobs/validationSchema.ts
server/routes/workProfile/workProfileController.ts
server/views/pages/candidateMatching/matchedJobs/partials/_matchedJobsFilters.njk

- implement matched jobs closing soon
- change request [ESWE-1112](https://dsdmoj.atlassian.net/browse/ESWE-1112), update release area filter content and validation

Eswe 1000 implement matched jobs closing soon

---

server/data/jobApi/getJobOfInterestClosingSoonResponse.ts
server/data/jobApi/jobApiClient.ts
server/routes/workProfile/workProfileController.ts

- Changed postcode to releaseArea
- Implemented expressions of interest closing soon
- Changed distance to searchRadius

ESWE-1000_implement_changes_to_backend_params 

---

server/data/jobApi/jobApiClient.ts
server/middleware/resolvers/getArchivedJobsResolver.ts
server/middleware/resolvers/getJobsOfInterestResolver.test.ts
server/middleware/resolvers/getJobsOfInterestResolver.ts
server/middleware/resolvers/utils/getJobsOfInterest.ts
server/routes/candidateMatching/jobsOfInterest/index.ts
server/views/pages/candidateMatching/jobsOfInterest/partials/_jobsOfInterestTable.njk

- Implemented new jobs of interest end point

ESWE-1000_implement_interested_jobs

---

README.md
integration_tests/e2e/login.cy.ts
server/views/pages/candidateMatching/prisonerListApplications/index.njk
server/views/pages/candidateMatching/prisonerListMatchJobs/index.njk
server/views/pages/homePage/index.njk
server/views/pages/workProfile/index.njk
server/views/pages/workReadiness/cohortList/index.njk

Changed Work after release to new title

change_application_name

---

server/views/pages/candidateMatching/prisonerListMatchJobs/partials/_notFoundMessages.njk
server/views/pages/candidateMatching/prisonerListMatchJobs/partials/_prisonerListTable.njk

- Fixed issue not showing messages

ESWE-1126_fix_no_found_messages  

---

server/middleware/resolvers/getApplicationProgressResolver.ts
server/middleware/resolvers/getArchivedJobsResolver.ts
server/middleware/resolvers/getJobDetailsResolver.ts
server/middleware/resolvers/getJobsOfInterestResolver.ts
server/middleware/resolvers/getMatchedJobsResolver.ts
server/middleware/resolvers/getPrisonerAddressByIdResolver.ts
server/middleware/resolvers/getPrisonerListApplicationsResolver.ts
server/middleware/resolvers/getPrisonerListMatchJobsResolver.ts
server/middleware/resolvers/utils/getApplicationProgress.ts
server/middleware/resolvers/utils/getArchivedJobs.ts
server/middleware/resolvers/utils/getClosedApplications.ts
server/middleware/resolvers/utils/getJobsOfInterest.ts
server/middleware/resolvers/utils/getJobsOfInterestClosingSoon.ts
server/middleware/resolvers/utils/getMatchedJobs.ts
server/middleware/resolvers/utils/getMatchedJobsClosingSoon.ts
server/middleware/resolvers/utils/getOpenApplications.ts
server/middleware/resolvers/utils/getPrisonerListApplications.ts
server/routes/candidateMatching/archivedJobs/archivedJobsController.ts
server/routes/candidateMatching/jobDetails/jobDetailsController.ts
server/routes/candidateMatching/jobsOfInterest/jobsOfInterestController.ts
server/routes/candidateMatching/manageApplication/manageApplicationController.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.test.ts
server/routes/candidateMatching/matchedJobs/matchedJobsController.ts
server/routes/candidateMatching/prisonerListApplications/prisonerListApplicationsController.ts
server/routes/candidateMatching/prisonerListMatchJobs/prisonerListMatchJobsController.ts
server/views/pages/workProfile/partials/_mjmaOverviewSection.njk

- Make matched jobs link always visible
- Change default search radius
- Fixed pagination on the prisoner list
- Added additional logging on MJMA
- Removed error 500 catch which was there for development only

Assorted day one fixes changes

---

server/views/pages/candidateMatching/prisonerListApplications/partials/_resultsPanel.njk

- Fixed results panel number display

results_panel_count_fix

---

server/data/jobApplicationApi/jobApplicationApiClient.ts
server/data/prisonerSearch/prisonerSearchClient.ts
server/middleware/resolvers/getPrisonerListApplicationsResolver.test.ts
server/middleware/resolvers/getUserRolesResolver.test.ts
server/middleware/resolvers/utils/getPrisonerListApplications.test.ts
server/middleware/resolvers/utils/getPrisonerListApplications.ts
server/services/jobApplicationService.test.ts
server/services/jobApplicationService.ts

- Added code to filter applications to valid prisoners
- Added code to not serve hidden files within assets

ESWE-1163 application list hide released

---

assets/sass/application.sass
server/middleware/setUpWebSecurity.ts
server/views/pages/candidateMatching/jobDetails/index.njk
server/views/pages/candidateMatching/matchedJobs/index.njk
server/views/pages/candidateMatching/matchedJobs/partials/_matchedJobsFilters.njk
server/views/pages/candidateMatching/matchedJobs/partials/_matchedJobsTable.njk
server/views/pages/workProfile/partials/_profileHeader.njk
server/views/pages/workProfile/partials/_toDoListSection.njk
server/views/pages/workReadiness/cohortList/partials/_cohortStatusRadios.njk
server/views/partials/layout.njk

- Hardened CSP rules
- Removed inline CSS styles

ESWE-1172 Security fixes

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
package-lock.json

Adjust CloudPlatform AlertManager receiver to route prometheus alerts to slack, [see here](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts)

fix alert severity channel to dps

---

server/middleware/setUpWebSecurity.ts
server/middleware/setUpWebSession.ts
server/utils/getAge.test.ts

Added cookie security settings
ESWE 1174
ESWE 1175
ESWE 1176

Cookie security

---

.eslintignore
package-lock.json
package.json
server/utils/getAge.test.ts
tsconfig.json

Update dependencies, inc.:
- [TypeScript](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-education-employment-ui/1698/workflows/c94f5e84-2236-49f1-8ef4-5df755d2a40d/jobs/6980)

dependencies and typescript update

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Adjust severity alerts after setting up alert manager. Alert severity are:
- dev / preprod: `education-alerts-non-prod`
- prod: `education-alerts`

update prometheus alerts

---

server/middleware/resolvers/getPrisonerListMatchJobsResolver.ts

- Added missing fields into cache

ESWE-1269_bug_fix_caching Fixed caching issues

---

server/views/pages/candidateMatching/jobDetails/index.njk
server/views/pages/candidateMatching/jobsOfInterest/partials/_jobsOfInterestTable.njk
server/views/pages/candidateMatching/manageApplication/index.njk
server/views/pages/candidateMatching/prisonerListApplications/partials/_applicationsListTable.njk
server/views/pages/workProfile/partials/_mjmaOverviewSection.njk

Unencode required fields from jobs and employers

FIX_encoded_characters_in_jobs 

---

server/views/pages/candidateMatching/archivedJobs/partials/_archivedJobsTable.njk
server/views/pages/candidateMatching/jobsOfInterest/partials/_jobsOfInterestTable.njk
server/views/pages/candidateMatching/manageApplication/partials/_applicationHistory.njk
server/views/pages/workReadiness/actions/editAction/partials/_notes.njk
server/views/pages/workReadiness/createProfile/checkYourAnswers/partials/_alreadyInPlace.njk
server/views/pages/workReadiness/createProfile/checkYourAnswers/partials/_eligibilityForSupport.njk
server/views/pages/workReadiness/createProfile/checkYourAnswers/partials/_workRelatedInfo.njk
server/views/pages/workReadiness/createProfile/identification/index.njk
server/views/pages/workReadiness/createProfile/jobOfParticularInterest/index.njk
server/views/pages/workReadiness/createProfile/supportDeclinedReason/index.njk
server/views/pages/workReadiness/createProfile/trainingAndQualifications/index.njk
server/views/pages/workReadiness/createProfile/typeOfWork/index.njk
server/views/pages/workReadiness/createProfile/whatNeedsToChange/index.njk
server/views/pages/workReadiness/createProfile/workExperience/index.njk

Decode details fields on edit and display

FIX_encoded_characters_details_fields

---

package-lock.json
package.json

Various dependencies, inc.:
| Package | Change |
|---|---|
| [@ministryofjustice/frontend](https://togithub.com/ministryofjustice/moj-frontend) | [`4.0.1` -> `5.1.2`]
| [typescript](https://www.typescriptlang.org/) ([source](https://togithub.com/Microsoft/TypeScript)) | [`5.8.2` -> `5.8.3`]

update various dependencies

---

server/routes/candidateMatching/prisonerListApplications/prisonerListApplicationsController.test.ts
server/routes/candidateMatching/prisonerListApplications/prisonerListApplicationsController.ts
server/routes/candidateMatching/prisonerListMatchJobs/prisonerListMatchJobsController.test.ts
server/routes/candidateMatching/prisonerListMatchJobs/prisonerListMatchJobsController.ts
server/routes/workReadiness/cohortList/cohortListController.test.ts
server/routes/workReadiness/cohortList/cohortListController.ts

Reduced the amount of data in the SEARCH audits to just identifiers.
Example test data...
Before:
```
{
correlationId: '0199a08d-b3d5-7556-99a9-c1bc615c1f21',
action: 'SEARCH_PRISONERS',
who: 'CWAUGH_GEN',
subjectType: 'SEARCH_TERM',
subjectId: '',
service: 'hmpps-education-employment-ui',
details: '{"userActiveCaseLoad":{"caseLoadId":"MDI","description":"Moorland (HMP & YOI)"},"prisonerNameFilter":"","typeOfWorkFilter":"","showNeedsSupportFilter":false}'
}
```
After:
```
{
correlationId: '0199a08d-b3d5-7556-99a9-c1bc615c1f21',
action: 'SEARCH_PRISONERS',
who: 'CWAUGH_GEN',
subjectType: 'SEARCH_TERM',
subjectId: '',
service: 'hmpps-education-employment-ui',
details: '{"userActiveCaseLoad":"MDI","prisonerNameFilter":"","typeOfWorkFilter":"","showNeedsSupportFilter":false}'
}
```
Before: …

ESWE-1110: Updated SEARCH audits
